### ISSUE TITLE
[Question] Should support to compare different generic type variables?

### ISSUE THREAD

**Issue by jolestar** [move-language/move#495] opened 2022-09-23 02:41 UTC
## To reproduce

**Code snippet to reproduce**
```move

//# publish
module 0x42.EQ{
    public test_eq<F, S>(f: &F, s: &S): bool {
    label b0:
        return move(f) == move(s);
    }
}

//# publish
module 0x42.M {
    struct T has drop { f: u64 }
    struct U has drop { f: u64 }

    public new_t(a: u64): Self.T {
    label b0:
        return T { f: move(a) };
    }

    public new_u(a: u64): Self.U {
    label b0:
        return U { f: move(a) };
    }
}

//# run
import 0x42.M;
import 0x42.EQ;

main() {
    let t: M.T;
    let t2: M.T;
    let u: M.U;
label b0:
    t = M.new_t(1);
    t2 = M.new_t(1);
    u = M.new_u(1);

    assert(EQ.test_eq<M.T,M.T>(&t, &t2), 42);
    assert(!EQ.test_eq<M.T,M.U>(&t, &u), 43);
    return;
}


```

**Stack trace/error message**
```
task 0 'publish'. lines 1-7:
Error: Unable to publish module '00000000000000000000000000000042::EQ'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::EQ,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
```

## Expected Behavior

The F and S may be the same, so `f == s` is possible.

## Additional context

The bytecode verifier requires the two operands of `Eq` and `Neq` must been same.

https://github.com/move-language/move/blob/0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa/language/move-bytecode-verifier/src/type_safety.rs#L646-L654

if we release the operands type check in the type_safety, and we need to check the container type in the VM runtime, otherwise the last assert will abort.

**Comment by jolestar** [comment] 2022-09-23 08:35
As discussed, this is intended behavior and not a bug.

Although sometimes we need to compare different generic types of variables, this is difficult to implement. if we implement such a method in Rust, need to write code like the following:

```rust
fn test_eq<F: Debug + std::cmp::PartialEq<S>, S: Debug + std::cmp::PartialEq<F>>(f: &F, s: &S) {
    if f == s {
        println!("{:?} == {:?}", f, s);
    } else {
        println!("{:?} != {:?}", f, s);
    }
}

#[test]
fn test() {
    let f = 1;
    let s = 2;
    test_eq(&f, &s);
}

```

**Comment by sblackshear** [comment] 2022-09-23 15:32
Closing since this is not a bug. Feel free to open a separate issue for comparing values of different types if there is a compelling motivation for this!

**Closed** 2022-09-23 15:31 UTC
Labels: question

**Comment by RxuqZ256** [comment] 2024-01-01 06:53
> ## To reproduce
> **Code snippet to reproduce**
> 
> ```move
> //# publish
> module 0x42.EQ{
>     public test_eq<F, S>(f: &F, s: &S): bool {
>     label b0:
>         return move(f) == move(s);
>     }
> }
> 
> //# publish
> module 0x42.M {
>     struct T has drop { f: u64 }
>     struct U has drop { f: u64 }
> 
>     public new_t(a: u64): Self.T {
>     label b0:
>         return T { f: move(a) };
>     }
> 
>     public new_u(a: u64): Self.U {
>     label b0:
>         return U { f: move(a) };
>     }
> }
> 
> //# run
> import 0x42.M;
> import 0x42.EQ;
> 
> main() {
>     let t: M.T;
>     let t2: M.T;
>     let u: M.U;
> label b0:
>     t = M.new_t(1);
>     t2 = M.new_t(1);
>     u = M.new_u(1);
> 
>     assert(EQ.test_eq<M.T,M.T>(&t, &t2), 42);
>     assert(!EQ.test_eq<M.T,M.U>(&t, &u), 43);
>     return;
> }
> ```
> 
> **Stack trace/error message**
> 
> ```
> task 0 'publish'. lines 1-7:
> Error: Unable to publish module '00000000000000000000000000000042::EQ'. Got VMError: {
>     major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
>     sub_status: None,
>     location: 0x42::EQ,
>     indices: [(FunctionDefinition, 0)],
>     offsets: [(FunctionDefinitionIndex(0), 2)],
> }
> ```
> 
> ## Expected Behavior
> The F and S may be the same, so `f == s` is possible.
> 
> ## Additional context
> The bytecode verifier requires the two operands of `Eq` and `Neq` must been same.
> 
> https://github.com/move-language/move/blob/0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa/language/move-bytecode-verifier/src/type_safety.rs#L646-L654
> 
> if we release the operands type check in the type_safety, and we need to check the container type in the VM runtime, otherwise the last assert will abort.
