### ISSUE TITLE
[Feature Request]Provide Table  drop ability when K, V both has drop ability

### ISSUE THREAD

**Issue by nkysg** [move-language/move#362] opened 2022-08-08 13:29 UTC
# 🚀 Feature Request

now table define as this
```rust
    struct Table<phantom K: copy + drop, phantom V> has store {
        handle: u128,
        length: u64,
    }
```
if we can provide drop ability when K, V both has drop ability? Thank you.
## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by nkysg** [comment] 2022-08-12 06:47
@wrwg could you look at this feature request, thanks!

**Comment by wrwg** [comment] 2022-08-13 17:02
Table has no drop capability because this feature is infeasible to implement for large tables. Tables are designed (in contrast to `SmallMap`) to be able to hold many millions of entries. Dropping a table of such size can be overly expensive to perform in one single transaction. It's like you are deleting an entire data base. Moreover, _accidentally_ dropping a data structure of this magnitude can be a fatal mistake from which there is no recovery. Perhaps you want to use `SmallMap`? In the newest code base, `SmallMap` now inherits the abilities of key and value.

Closing since working as designed.

**Closed by wrwg** 2022-08-13 17:02 UTC
Labels: enhancement
