### ISSUE TITLE
[Feature Request] Create a standard move library repo

### ISSUE THREAD

**Issue by aranoverse** [move-language/move#320] opened 2022-07-29 15:19 UTC
# 🚀 Feature Request

Maybe we should create a standard move library repo like the [open-zeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) in solidity .

## Motivation

Standard contracts library is a very efficient helper.

**Comment by sblackshear** [comment] 2022-08-09 17:11
Duplicate of https://github.com/move-language/move/issues/345

**Closed by sblackshear** 2022-08-09 17:11 UTC
Labels: enhancement
